// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.aeiou.bigbang.domain;

import com.aeiou.bigbang.domain.BigTag;
import com.aeiou.bigbang.domain.BigTagDataOnDemand;
import com.aeiou.bigbang.domain.BigTagIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BigTagIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BigTagIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BigTagIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BigTagIntegrationTest: @Transactional;
    
    @Autowired
    private BigTagDataOnDemand BigTagIntegrationTest.dod;
    
    @Test
    public void BigTagIntegrationTest.testCountBigTags() {
        Assert.assertNotNull("Data on demand for 'BigTag' failed to initialize correctly", dod.getRandomBigTag());
        long count = BigTag.countBigTags();
        Assert.assertTrue("Counter for 'BigTag' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BigTagIntegrationTest.testFindBigTag() {
        BigTag obj = dod.getRandomBigTag();
        Assert.assertNotNull("Data on demand for 'BigTag' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BigTag' failed to provide an identifier", id);
        obj = BigTag.findBigTag(id);
        Assert.assertNotNull("Find method for 'BigTag' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'BigTag' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BigTagIntegrationTest.testFindAllBigTags() {
        Assert.assertNotNull("Data on demand for 'BigTag' failed to initialize correctly", dod.getRandomBigTag());
        long count = BigTag.countBigTags();
        Assert.assertTrue("Too expensive to perform a find all test for 'BigTag', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<BigTag> result = BigTag.findAllBigTags();
        Assert.assertNotNull("Find all method for 'BigTag' illegally returned null", result);
        Assert.assertTrue("Find all method for 'BigTag' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BigTagIntegrationTest.testFindBigTagEntries() {
        Assert.assertNotNull("Data on demand for 'BigTag' failed to initialize correctly", dod.getRandomBigTag());
        long count = BigTag.countBigTags();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<BigTag> result = BigTag.findBigTagEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'BigTag' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'BigTag' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BigTagIntegrationTest.testFlush() {
        BigTag obj = dod.getRandomBigTag();
        Assert.assertNotNull("Data on demand for 'BigTag' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BigTag' failed to provide an identifier", id);
        obj = BigTag.findBigTag(id);
        Assert.assertNotNull("Find method for 'BigTag' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBigTag(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'BigTag' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BigTagIntegrationTest.testMergeUpdate() {
        BigTag obj = dod.getRandomBigTag();
        Assert.assertNotNull("Data on demand for 'BigTag' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BigTag' failed to provide an identifier", id);
        obj = BigTag.findBigTag(id);
        boolean modified =  dod.modifyBigTag(obj);
        Integer currentVersion = obj.getVersion();
        BigTag merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'BigTag' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BigTagIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'BigTag' failed to initialize correctly", dod.getRandomBigTag());
        BigTag obj = dod.getNewTransientBigTag(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'BigTag' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'BigTag' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'BigTag' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BigTagIntegrationTest.testRemove() {
        BigTag obj = dod.getRandomBigTag();
        Assert.assertNotNull("Data on demand for 'BigTag' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BigTag' failed to provide an identifier", id);
        obj = BigTag.findBigTag(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'BigTag' with identifier '" + id + "'", BigTag.findBigTag(id));
    }
    
}
