// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.aeiou.bigbang.domain;

import com.aeiou.bigbang.domain.Content;
import com.aeiou.bigbang.domain.ContentDataOnDemand;
import com.aeiou.bigbang.domain.ContentIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ContentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ContentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ContentIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ContentIntegrationTest: @Transactional;
    
    @Autowired
    ContentDataOnDemand ContentIntegrationTest.dod;
    
    @Test
    public void ContentIntegrationTest.testCountContents() {
        Assert.assertNotNull("Data on demand for 'Content' failed to initialize correctly", dod.getRandomContent());
        long count = Content.countContents();
        Assert.assertTrue("Counter for 'Content' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ContentIntegrationTest.testFindContent() {
        Content obj = dod.getRandomContent();
        Assert.assertNotNull("Data on demand for 'Content' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Content' failed to provide an identifier", id);
        obj = Content.findContent(id);
        Assert.assertNotNull("Find method for 'Content' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Content' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ContentIntegrationTest.testFindAllContents() {
        Assert.assertNotNull("Data on demand for 'Content' failed to initialize correctly", dod.getRandomContent());
        long count = Content.countContents();
        Assert.assertTrue("Too expensive to perform a find all test for 'Content', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Content> result = Content.findAllContents();
        Assert.assertNotNull("Find all method for 'Content' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Content' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ContentIntegrationTest.testFindContentEntries() {
        Assert.assertNotNull("Data on demand for 'Content' failed to initialize correctly", dod.getRandomContent());
        long count = Content.countContents();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Content> result = Content.findContentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Content' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Content' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ContentIntegrationTest.testFlush() {
        Content obj = dod.getRandomContent();
        Assert.assertNotNull("Data on demand for 'Content' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Content' failed to provide an identifier", id);
        obj = Content.findContent(id);
        Assert.assertNotNull("Find method for 'Content' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyContent(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Content' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContentIntegrationTest.testMergeUpdate() {
        Content obj = dod.getRandomContent();
        Assert.assertNotNull("Data on demand for 'Content' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Content' failed to provide an identifier", id);
        obj = Content.findContent(id);
        boolean modified =  dod.modifyContent(obj);
        Integer currentVersion = obj.getVersion();
        Content merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Content' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Content' failed to initialize correctly", dod.getRandomContent());
        Content obj = dod.getNewTransientContent(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Content' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Content' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Content' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ContentIntegrationTest.testRemove() {
        Content obj = dod.getRandomContent();
        Assert.assertNotNull("Data on demand for 'Content' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Content' failed to provide an identifier", id);
        obj = Content.findContent(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Content' with identifier '" + id + "'", Content.findContent(id));
    }
    
}
