// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.aeiou.bigbang.domain;

import com.aeiou.bigbang.domain.Content;
import com.aeiou.bigbang.domain.ContentDataOnDemand;
import com.aeiou.bigbang.domain.UserAccount;
import com.aeiou.bigbang.domain.UserAccountDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ContentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ContentDataOnDemand: @Component;
    
    private Random ContentDataOnDemand.rnd = new SecureRandom();
    
    private List<Content> ContentDataOnDemand.data;
    
    @Autowired
    private UserAccountDataOnDemand ContentDataOnDemand.userAccountDataOnDemand;
    
    public Content ContentDataOnDemand.getNewTransientContent(int index) {
        Content obj = new Content();
        setConentCache(obj, index);
        setPublisher(obj, index);
        setSourceURL(obj, index);
        setTitle(obj, index);
        return obj;
    }
    
    public void ContentDataOnDemand.setConentCache(Content obj, int index) {
        String conentCache = "conentCache_" + index;
        obj.setConentCache(conentCache);
    }
    
    public void ContentDataOnDemand.setPublisher(Content obj, int index) {
        UserAccount publisher = userAccountDataOnDemand.getRandomUserAccount();
        obj.setPublisher(publisher);
    }
    
    public void ContentDataOnDemand.setSourceURL(Content obj, int index) {
        String sourceURL = "sourceURL_" + index;
        obj.setSourceURL(sourceURL);
    }
    
    public void ContentDataOnDemand.setTitle(Content obj, int index) {
        String title = "title_" + index;
        obj.setTitle(title);
    }
    
    public Content ContentDataOnDemand.getSpecificContent(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Content obj = data.get(index);
        Long id = obj.getId();
        return Content.findContent(id);
    }
    
    public Content ContentDataOnDemand.getRandomContent() {
        init();
        Content obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Content.findContent(id);
    }
    
    public boolean ContentDataOnDemand.modifyContent(Content obj) {
        return false;
    }
    
    public void ContentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Content.findContentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Content' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Content>();
        for (int i = 0; i < 10; i++) {
            Content obj = getNewTransientContent(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
