// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.aeiou.bigbang.domain;

import com.aeiou.bigbang.domain.Customize;
import com.aeiou.bigbang.domain.CustomizeDataOnDemand;
import com.aeiou.bigbang.domain.UserAccountDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CustomizeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CustomizeDataOnDemand: @Component;
    
    private Random CustomizeDataOnDemand.rnd = new SecureRandom();
    
    private List<Customize> CustomizeDataOnDemand.data;
    
    @Autowired
    UserAccountDataOnDemand CustomizeDataOnDemand.userAccountDataOnDemand;
    
    public Customize CustomizeDataOnDemand.getNewTransientCustomize(int index) {
        Customize obj = new Customize();
        setCusKey(obj, index);
        setCusValue(obj, index);
        return obj;
    }
    
    public void CustomizeDataOnDemand.setCusKey(Customize obj, int index) {
        String cusKey = "cusKey_" + index;
        obj.setCusKey(cusKey);
    }
    
    public void CustomizeDataOnDemand.setCusValue(Customize obj, int index) {
        String cusValue = "cusValue_" + index;
        obj.setCusValue(cusValue);
    }
    
    public Customize CustomizeDataOnDemand.getSpecificCustomize(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Customize obj = data.get(index);
        Long id = obj.getId();
        return Customize.findCustomize(id);
    }
    
    public Customize CustomizeDataOnDemand.getRandomCustomize() {
        init();
        Customize obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Customize.findCustomize(id);
    }
    
    public boolean CustomizeDataOnDemand.modifyCustomize(Customize obj) {
        return false;
    }
    
    public void CustomizeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Customize.findCustomizeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Customize' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Customize>();
        for (int i = 0; i < 10; i++) {
            Customize obj = getNewTransientCustomize(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
