// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.aeiou.bigbang.domain;

import com.aeiou.bigbang.domain.RemarkIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RemarkIntegrationTest_Roo_Configurable {
    
    declare @type: RemarkIntegrationTest: @Configurable;
    
}
