// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.aeiou.bigbang.domain;

import com.aeiou.bigbang.domain.Remark;
import com.aeiou.bigbang.domain.RemarkDataOnDemand;
import com.aeiou.bigbang.domain.RemarkIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RemarkIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RemarkIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RemarkIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RemarkIntegrationTest: @Transactional;
    
    @Autowired
    RemarkDataOnDemand RemarkIntegrationTest.dod;
    
    @Test
    public void RemarkIntegrationTest.testCountRemarks() {
        Assert.assertNotNull("Data on demand for 'Remark' failed to initialize correctly", dod.getRandomRemark());
        long count = Remark.countRemarks();
        Assert.assertTrue("Counter for 'Remark' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RemarkIntegrationTest.testFindRemark() {
        Remark obj = dod.getRandomRemark();
        Assert.assertNotNull("Data on demand for 'Remark' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Remark' failed to provide an identifier", id);
        obj = Remark.findRemark(id);
        Assert.assertNotNull("Find method for 'Remark' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Remark' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RemarkIntegrationTest.testFindAllRemarks() {
        Assert.assertNotNull("Data on demand for 'Remark' failed to initialize correctly", dod.getRandomRemark());
        long count = Remark.countRemarks();
        Assert.assertTrue("Too expensive to perform a find all test for 'Remark', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Remark> result = Remark.findAllRemarks();
        Assert.assertNotNull("Find all method for 'Remark' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Remark' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RemarkIntegrationTest.testFindRemarkEntries() {
        Assert.assertNotNull("Data on demand for 'Remark' failed to initialize correctly", dod.getRandomRemark());
        long count = Remark.countRemarks();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Remark> result = Remark.findRemarkEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Remark' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Remark' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RemarkIntegrationTest.testFlush() {
        Remark obj = dod.getRandomRemark();
        Assert.assertNotNull("Data on demand for 'Remark' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Remark' failed to provide an identifier", id);
        obj = Remark.findRemark(id);
        Assert.assertNotNull("Find method for 'Remark' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRemark(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Remark' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RemarkIntegrationTest.testMergeUpdate() {
        Remark obj = dod.getRandomRemark();
        Assert.assertNotNull("Data on demand for 'Remark' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Remark' failed to provide an identifier", id);
        obj = Remark.findRemark(id);
        boolean modified =  dod.modifyRemark(obj);
        Integer currentVersion = obj.getVersion();
        Remark merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Remark' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RemarkIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Remark' failed to initialize correctly", dod.getRandomRemark());
        Remark obj = dod.getNewTransientRemark(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Remark' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Remark' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Remark' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RemarkIntegrationTest.testRemove() {
        Remark obj = dod.getRandomRemark();
        Assert.assertNotNull("Data on demand for 'Remark' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Remark' failed to provide an identifier", id);
        obj = Remark.findRemark(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Remark' with identifier '" + id + "'", Remark.findRemark(id));
    }
    
}
