// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.aeiou.bigbang.domain;

import com.aeiou.bigbang.domain.RssTwitter;
import com.aeiou.bigbang.domain.RssTwitterDataOnDemand;
import com.aeiou.bigbang.domain.RssTwitterIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RssTwitterIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RssTwitterIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RssTwitterIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RssTwitterIntegrationTest: @Transactional;
    
    @Autowired
    private RssTwitterDataOnDemand RssTwitterIntegrationTest.dod;
    
    @Test
    public void RssTwitterIntegrationTest.testCountRssTwitters() {
        Assert.assertNotNull("Data on demand for 'RssTwitter' failed to initialize correctly", dod.getRandomRssTwitter());
        long count = RssTwitter.countRssTwitters();
        Assert.assertTrue("Counter for 'RssTwitter' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RssTwitterIntegrationTest.testFindRssTwitter() {
        RssTwitter obj = dod.getRandomRssTwitter();
        Assert.assertNotNull("Data on demand for 'RssTwitter' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RssTwitter' failed to provide an identifier", id);
        obj = RssTwitter.findRssTwitter(id);
        Assert.assertNotNull("Find method for 'RssTwitter' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'RssTwitter' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RssTwitterIntegrationTest.testFindAllRssTwitters() {
        Assert.assertNotNull("Data on demand for 'RssTwitter' failed to initialize correctly", dod.getRandomRssTwitter());
        long count = RssTwitter.countRssTwitters();
        Assert.assertTrue("Too expensive to perform a find all test for 'RssTwitter', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<RssTwitter> result = RssTwitter.findAllRssTwitters();
        Assert.assertNotNull("Find all method for 'RssTwitter' illegally returned null", result);
        Assert.assertTrue("Find all method for 'RssTwitter' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RssTwitterIntegrationTest.testFindRssTwitterEntries() {
        Assert.assertNotNull("Data on demand for 'RssTwitter' failed to initialize correctly", dod.getRandomRssTwitter());
        long count = RssTwitter.countRssTwitters();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<RssTwitter> result = RssTwitter.findRssTwitterEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'RssTwitter' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'RssTwitter' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RssTwitterIntegrationTest.testFlush() {
        RssTwitter obj = dod.getRandomRssTwitter();
        Assert.assertNotNull("Data on demand for 'RssTwitter' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RssTwitter' failed to provide an identifier", id);
        obj = RssTwitter.findRssTwitter(id);
        Assert.assertNotNull("Find method for 'RssTwitter' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRssTwitter(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'RssTwitter' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RssTwitterIntegrationTest.testMergeUpdate() {
        RssTwitter obj = dod.getRandomRssTwitter();
        Assert.assertNotNull("Data on demand for 'RssTwitter' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RssTwitter' failed to provide an identifier", id);
        obj = RssTwitter.findRssTwitter(id);
        boolean modified =  dod.modifyRssTwitter(obj);
        Integer currentVersion = obj.getVersion();
        RssTwitter merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'RssTwitter' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RssTwitterIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'RssTwitter' failed to initialize correctly", dod.getRandomRssTwitter());
        RssTwitter obj = dod.getNewTransientRssTwitter(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'RssTwitter' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'RssTwitter' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'RssTwitter' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RssTwitterIntegrationTest.testRemove() {
        RssTwitter obj = dod.getRandomRssTwitter();
        Assert.assertNotNull("Data on demand for 'RssTwitter' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RssTwitter' failed to provide an identifier", id);
        obj = RssTwitter.findRssTwitter(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'RssTwitter' with identifier '" + id + "'", RssTwitter.findRssTwitter(id));
    }
    
}
